name: CI/CD with DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/9oorm-ai
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest

    # 서버에 배포
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: halim7753
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        script: |
          docker stop 9oorm-ai || true
          docker rm 9oorm-ai || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/9oorm-ai:latest
          docker run -d --name 9oorm-ai -p 8000:8000 \
            --network 9oorm-network \
            -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/9oorm-ai:latest

